# Site Settings
title: "Mafiakitty Sailing"
email: themafiakitty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Follow Mike and Michelle as they frugally sail around the world while trying to surive off the grid.
baseurl: ""
url: ""
twitter_username: themafiakitty
permalink: /:year/:month/:day/:title.html

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
