title: Mafia Kitty Sailing
description: The adventures of Mike and Michelle.

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Articles
   url: /articles
 - title: Videos
   url: /#coming-soon
 - title: The Crew
   url: /crew
 - title: The Boat
   url: /boat
 - title: Contact
   url: /contact

social:
   github: michealkennedy
   twitter: michealkennedy
   facebook: michealkennedy
   email: themafiakitty@gmail.com

google_analytics: "UA-85169909-1"
